npmRegistries:
  "https://npm.pkg.github.com/":
    npmAuthToken: "${NPM_CONFIG_GITHUB_TOKEN}"

npmScopes:
  rockefeller-center:
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
